# Generated by Django 4.2.11 on 2024-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollars'), ('INR', 'Inr')], default='USD', max_length=8),
        ),
    ]
