# Generated by Django 4.2.11 on 2024-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_pricing_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='duration',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='pricing',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], default='IN', max_length=10),
        ),
    ]
