# Generated by Django 4.2.13 on 2024-05-12 08:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0012_alter_transaction_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='ProvisionalOrder',
        ),
    ]
