# Generated by Django 4.2.13 on 2024-05-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_order_provisionalorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provisional_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.provisionalorder')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
