# Generated by Django 4.2.13 on 2024-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_paymentgatewayresponse_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='insukoon_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
