# Generated by Django 4.2.13 on 2024-05-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_order_insukoon_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='bin_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='retry',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='trans_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayresponse',
            name='vault',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
