# Generated by Django 4.2.3 on 2024-03-01 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=20)),
                ('classes_start_from', models.CharField(max_length=100)),
                ('classes_end_to', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('director_phone_number', models.CharField(max_length=20)),
                ('director_email', models.EmailField(max_length=254)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_phone_number', models.CharField(max_length=20)),
                ('principal_email', models.EmailField(max_length=254)),
                ('poc_name', models.CharField(max_length=100)),
                ('poc_mobile_number', models.CharField(max_length=20)),
                ('poc_email', models.EmailField(max_length=254)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('avg_class_size', models.PositiveIntegerField(default=0)),
                ('kg_students', models.PositiveIntegerField(default=0)),
                ('grade_1_5_students', models.PositiveIntegerField(default=0)),
                ('grade_6_8_students', models.PositiveIntegerField(default=0)),
                ('grade_9_12_students', models.PositiveIntegerField(default=0)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('total_non_teaching_staff', models.PositiveIntegerField(default=0)),
                ('kg_teachers', models.PositiveIntegerField(default=0)),
                ('grade_1_5_teachers', models.PositiveIntegerField(default=0)),
                ('grade_6_8_teachers', models.PositiveIntegerField(default=0)),
                ('grade_9_12_teachers', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_dob', models.DateField(default='2005-11-01')),
                ('student_gender', models.CharField(max_length=10)),
                ('student_country', models.CharField(max_length=100)),
                ('student_state', models.CharField(max_length=100)),
                ('student_grade', models.CharField(max_length=100)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('father_email', models.EmailField(max_length=254)),
                ('father_mobile_number', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('mother_email', models.EmailField(max_length=254)),
                ('mother_mobile_number', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mobile_number_verification', models.BooleanField(default=False)),
                ('email_verification', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
