# Generated by Django 4.2.3 on 2024-02-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_schoolprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='avg_class_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_1_5_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_1_5_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_6_8_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_6_8_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_9_12_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_9_12_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='kg_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='kg_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='total_non_teaching_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='total_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
