# Generated by Django 4.2.13 on 2024-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_parentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='total_students',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
