# Generated by Django 4.2.13 on 2024-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_schoolprofile_total_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_as_parent_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_as_parent_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_as_parent_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_in_child_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_in_child_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_in_child_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_in_child_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='areas_to_improve_in_child_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='batch_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='batch_time',
            field=models.CharField(choices=[('4:00 PM - 5:00 PM', '4:00 PM - 5:00 PM'), ('5:00 PM - 6:00 PM', '5:00 PM - 6:00 PM'), ('6:00 PM - 7:00 PM', '6:00 PM - 7:00 PM'), ('7:00 PM - 8:00 PM', '7:00 PM - 8:00 PM'), ('8:00 PM - 9:00 PM', '8:00 PM - 9:00 PM')], default='4:00 PM - 5:00', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Mix of Both', 'Mix of Both')], default='Mix of Both', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='preferred_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='session_day',
            field=models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], default='Weekday', max_length=10),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='session_time',
            field=models.CharField(choices=[('Before 8 PM', 'Before 8 PM'), ('After 8 PM', 'After 8 PM')], default='After 8 PM', max_length=20),
        ),
    ]
