# Generated by Django 4.2.13 on 2024-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_parentprofile_areas_to_improve_as_parent_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='program_1_name',
            field=models.CharField(blank=True, choices=[('Kindergarten', 'Kindergarten'), ('Primary', 'Primary Schooler (Grade 1-5)'), ('PreTeens', 'Pre-Teens (6-8)'), ('Teens', 'Teens (9-10)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_1_student_batch_time',
            field=models.CharField(blank=True, choices=[('During', 'During School Hours'), ('After', 'After School Hours')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_1_student_session_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_2_name',
            field=models.CharField(blank=True, choices=[('Gurutva', "Gurutva (Teacher's Program)"), ('Samarpan', 'Samarpan (Staff Program)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_2_staff_batch_time',
            field=models.CharField(blank=True, choices=[('During', 'During School Hours'), ('After', 'After School Hours')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_2_staff_session_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_2_teacher_batch_time',
            field=models.CharField(blank=True, choices=[('During', 'During School Hours'), ('After', 'After School Hours')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='program_2_teacher_session_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
    ]
