# Generated by Django 4.2.13 on 2024-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_schoolprofile_program_1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentprofile',
            old_name='email_verification',
            new_name='notification_email',
        ),
        migrations.RenameField(
            model_name='parentprofile',
            old_name='mobile_number_verification',
            new_name='notification_phone_number',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
