# Generated by Django 4.2.13 on 2024-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_rename_transaction_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='usage_limit',
            field=models.IntegerField(default=100000),
        ),
    ]
