# Generated by Django 4.2.3 on 2024-03-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_rename_referral_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrer',
            old_name='user_id',
            new_name='user',
        ),
    ]
