# Generated by Django 4.2.3 on 2024-03-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
