# Generated by Django 4.2.3 on 2024-03-08 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_rename_email_verified_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
    ]
