# Generated by Django 4.2.11 on 2024-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], default='IN', max_length=10),
        ),
    ]
