# Generated by Django 4.2.11 on 2024-04-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], max_length=10),
        ),
    ]
